#!/usr/bin/env ruby

require 'nomadize'

def migration_name
  ARGV.fetch(1)
rescue IndexError
  abort 'Error: Migration name not provided'
end

case ARGV[0]
when 'create' then Nomadize.create_database
when 'drop' then Nomadize.drop_database
when 'new_migration' then Nomadize.generate_template_migration_file(migration_name)
when 'migrate' then Nomadize.migrate
when 'status' then Nomadize.status
when 'rollback' then Nomadize.rollback(ARGV.fetch(1, 1))
when nil then abort 'Error: No Command Provided'
else abort "Error: Unknown Command '#{ARGV[0]}'"
end
